<a href="https://colab.research.google.com/github/thproger/dotnet-bot/blob/main/content/02-getting-started/jupyter_notebooks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_gradient(x):
    return sigmoid(x) * (1 - sigmoid(x))

In [3]:
import numpy as np
import matplotlib.pyplot as plt

X = np.array([[1]])
Y = np.array([[1]]).T

np.random.seed(1)
weights = np.random.random((X.shape[1], 1))
bias = np.random.random((1, 1))

display(weights, bias)

array([[0.417022]])

array([[0.72032449]])

In [6]:
output = X * weights + bias
pred = sigmoid(output)
pred

array([[0.75719212]])

In [8]:
(Y-pred)**2

array([[0.05895567]])

Back propagation

In [13]:
dsigma = 2 * (pred - Y)
db = sigmoid_gradient(output) * dsigma
# Усе інше одинички
dW1 = db * X
dW1

array([[-0.08928153]])

In [ ]:
bias -= dW1
weights -= dW1

In [14]:
pred = sigmoid(np.dot(X, weights) + bias)
pred

array([[0.75719212]])

Те саме через keras

In [19]:
from keras.layers import Dense
from keras.models import Sequential
import tensorflow as tf

model = Sequential([
    Dense(1, input_shape=(1,), activation='sigmoid')
])

model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
X_toy = tf.constant([1])
Y_toy = tf.constant([1])

Градієнтний спуск

In [23]:

optimizer = tf.keras.optimizers.SGD(learning_rate=1.0)
loss_fn = tf.keras.losses.MSE

In [25]:
params = [np.empty(shape = (1,1), dtype = np.float32), np.empty(shape = (1,), dtype = np.float32)]
params[0][0] = 0.417
params[1][0] = 0.72

model.set_weights(params)
model.get_weights()

[array([[0.417]], dtype=float32), array([0.72], dtype=float32)]

In [29]:
for epoch in range(100):
    with tf.GradientTape() as tape:
      # прямий прохід
        pred = model(X_toy)
        print('Prediction is', pred.numpy())

        loss_value = loss_fn(Y_toy, pred)
        print('Loss is', loss_value.numpy())

        # Зворотній прохід
        grads = tape.gradient(loss_value, model.trainable_weights)
        print('Grad are', grads)

    optimizer.apply_gradients(zip(grads, model.trainable_weights))

Prediction is [[0.7884557]]
Loss is [0.04475098]
Grad are [<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.07056834]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.07056834], dtype=float32)>]
Prediction is [[0.81103945]]
Loss is [0.03570609]
Grad are [<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.0579181]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.0579181], dtype=float32)>]
Prediction is [[0.828156]]
Loss is [0.02953036]
Grad are [<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.04891149]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.04891149], dtype=float32)>]
Prediction is [[0.84163415]]
Loss is [0.02507974]
Grad are [<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.04221593]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.04221593], dtype=float32)>]
Prediction is [[0.85256594]]
Loss is [0.0217368]
Grad are [<tf.Tensor: shape=(1, 1), 

In [30]:
model.get_weights()

[array([[1.47939]], dtype=float32), array([1.7823898], dtype=float32)]

In [31]:
model(X_toy)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.9630941]], dtype=float32)>

In [32]:
np.mean((Y - pred)**2)

np.float32(0.0013760177)

In [40]:
X_toy = tf.constant([[0.0], [1.0]])
y_toy = tf.constant([[0.0], [1.0]])

In [41]:
from keras.layers import Dense
from keras.models import Sequential
import tensorflow as tf

tf.random.set_seed(1)
model = Sequential([
    Dense(1, input_shape=(1,), activation='sigmoid')
])

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [42]:
params = [np.empty(shape = (1,1), dtype = np.float32), np.empty(shape = (1,), dtype = np.float32)]
params[0][0] = 0.417
params[1][0] = 0.72

model.set_weights(params)
model.get_weights()

[array([[0.417]], dtype=float32), array([0.72], dtype=float32)]

In [43]:
for epoch in range(1):
    with tf.GradientTape() as tape:
        pred = model(X_toy)
        print('Prediction is', pred.numpy())

        loss_value = loss_fn(y_toy, pred)
        print('Loss is', loss_value.numpy())

        grads = tape.gradient(loss_value, model.trainable_weights)
        print('Grad are', grads)

    optimizer.apply_gradients(zip(grads, model.trainable_weights))

Prediction is [[0.672607 ]
 [0.7571285]]
Loss is [0.45240018 0.05898658]
Grad are [<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.08932084]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.20690447], dtype=float32)>]


ValueError: Unknown variable: <Variable path=sequential_4/dense_4/kernel, shape=(1, 1), dtype=float32, value=[[0.417]]>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.